class CellObj(object):
	def __init__(self):
		self.x = self.y = self.z = 0
		self.create_sections()
		self.build_topology()
		self.build_subsets()
		self.define_geometry()
		self.define_biophysics()

	def create_sections(self):
		self.soma = h.Section(name=soma, cell=self)
		self.dend = h.Section(name=dend0, cell=self)
		self.dend = h.Section(name=dend1, cell=self)
		self.dend = h.Section(name=dend2, cell=self)
		self.dend = h.Section(name=dend3, cell=self)
		self.dend = h.Section(name=dend4, cell=self)
		self.dend = h.Section(name=dend5, cell=self)
		self.dend = h.Section(name=dend6, cell=self)
		self.dend = h.Section(name=dend7, cell=self)
		self.dend = h.Section(name=dend8, cell=self)
		self.dend = h.Section(name=dend9, cell=self)
		self.dend = h.Section(name=dend10, cell=self)
		self.dend = h.Section(name=dend11, cell=self)
		self.dend = h.Section(name=dend12, cell=self)
		self.dend = h.Section(name=dend13, cell=self)
		self.dend = h.Section(name=dend14, cell=self)
		self.dend = h.Section(name=dend15, cell=self)
		self.dend = h.Section(name=dend16, cell=self)
		self.dend = h.Section(name=dend17, cell=self)
		self.dend = h.Section(name=dend18, cell=self)
		self.dend = h.Section(name=dend19, cell=self)
		self.dend = h.Section(name=dend20, cell=self)
		self.dend = h.Section(name=dend21, cell=self)
		self.dend = h.Section(name=dend22, cell=self)
		self.dend = h.Section(name=dend23, cell=self)
		self.dend = h.Section(name=dend24, cell=self)
		self.dend = h.Section(name=dend25, cell=self)
		self.dend = h.Section(name=dend26, cell=self)
		self.dend = h.Section(name=dend27, cell=self)
		self.dend = h.Section(name=dend28, cell=self)
		self.dend = h.Section(name=dend29, cell=self)
		self.dend = h.Section(name=dend30, cell=self)
		self.dend = h.Section(name=dend31, cell=self)
		self.dend = h.Section(name=dend32, cell=self)
		self.dend = h.Section(name=dend33, cell=self)
		self.dend = h.Section(name=dend34, cell=self)
		self.dend = h.Section(name=dend35, cell=self)
		self.dend = h.Section(name=dend36, cell=self)
		self.apic = h.Section(name=apic0, cell=self)
		self.apic = h.Section(name=apic1, cell=self)
		self.apic = h.Section(name=apic2, cell=self)
		self.apic = h.Section(name=apic3, cell=self)
		self.apic = h.Section(name=apic4, cell=self)
		self.apic = h.Section(name=apic5, cell=self)
		self.apic = h.Section(name=apic6, cell=self)
		self.apic = h.Section(name=apic7, cell=self)
		self.apic = h.Section(name=apic8, cell=self)
		self.apic = h.Section(name=apic9, cell=self)
		self.apic = h.Section(name=apic10, cell=self)
		self.apic = h.Section(name=apic11, cell=self)
		self.apic = h.Section(name=apic12, cell=self)
		self.apic = h.Section(name=apic13, cell=self)
		self.apic = h.Section(name=apic14, cell=self)
		self.apic = h.Section(name=apic15, cell=self)
		self.apic = h.Section(name=apic16, cell=self)
		self.apic = h.Section(name=apic17, cell=self)
		self.apic = h.Section(name=apic18, cell=self)
		self.apic = h.Section(name=apic19, cell=self)
		self.apic = h.Section(name=apic20, cell=self)
		self.apic = h.Section(name=apic21, cell=self)
		self.apic = h.Section(name=apic22, cell=self)
		self.apic = h.Section(name=apic23, cell=self)
		self.apic = h.Section(name=apic24, cell=self)
		self.apic = h.Section(name=apic25, cell=self)
		self.apic = h.Section(name=apic26, cell=self)
		self.apic = h.Section(name=apic27, cell=self)
		self.apic = h.Section(name=apic28, cell=self)
		self.apic = h.Section(name=apic29, cell=self)
		self.apic = h.Section(name=apic30, cell=self)
		self.apic = h.Section(name=apic31, cell=self)
		self.apic = h.Section(name=apic32, cell=self)
		self.apic = h.Section(name=apic33, cell=self)
		self.apic = h.Section(name=apic34, cell=self)
		self.axon = h.Section(name=axon, cell=self)

#end